name: conda
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python
  - pip
  - pip:
    - numpy==1.23.5
    - pydicom==2.4.4
    - scikit-image==0.20.0
    - tensorflow==2.12.0
    - tqdm==4.65.0
    - pytest==7.4.0
    - click==8.0.4
    - azure-ai-ml==1.12.1
