FROM continuumio/miniconda3

RUN pip install --upgrade pip

RUN pip install numpy==1.23.5
RUN pip install pydicom==2.4.4
RUN pip install scikit-image==0.20.0
RUN pip install tensorflow==2.12.0
RUN pip install tqdm==4.65.0
RUN pip install pytest==7.4.0
RUN pip install click==8.0.4
RUN pip install azure-ai-ml==1.12.1
RUN pip install tensorflow-addons==0.23.0

